config/routes.rb
Rails.application.routes.draw do
  

   devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  

  
  get 'users/index'
  get 'tags/:tag', to: 'forms#tagss', as: :tag 
 

  devise_for :users, :controllers => { sessions: "users/sessions", :registrations => 'users/registrations',
                                       :confirmations => 'users/confirmations', :passwords => 'users/passwords', omniauth_callbacks: "users/omniauth_callbacks"}

  resources :user_steps

  get '/:id/new_form' => 'forms#new_modal'
  get '/:id/:slug_url/edit_form' => 'forms#edit_modal'
  get '/:id/:slug_url/get_form_data' => 'forms#get_form_data'
  post '/:id/:slug_url/update_form' => 'forms#update_form'
  get '/:id/:slug_url/get_meta_data' => 'forms#get_meta_data'
  get '/:id/get_meta_data' => 'forms#get_meta_data'
  post '/:id/create_form' => 'forms#create_form'

  get '/users/categories' => 'users#categories'
  post '/users/update_categories' => 'users#update_categories'  
  
  get '/admin_forms' => 'forms#admin_index'
  get '/get_forms' => 'forms#get_admin_forms'
  resources :forms, :only => [:index, :edit, :update, :destroy] do
    member do
      get "like"
      get "unlike"
      get "book"
      get "booknot"
      put "difficulty", to: "forms#difficulty"
    end
  end

  resources :users, :only => [:index, :show, :edit, :update] do
    member do
      get 'categories' => 'users#categories'
      post 'update_categories' => 'users#update_categories'
      post 'link_clicked' => 'users#link_clicked' 
    end
    resources :follows, :only => [:create, :destroy]
  end

  resources :profile_validation, only: [:index]
  
  resources :categories, :only => [:index, :new, :create, :update, :destroy, :edit]
  get '/categories/:name' => 'static_pages#categories'

  get '/following' => 'follows#following'
  get '/followers' => 'follows#followers'

  resources :follows, :only => [:create, :destroy]

  get '/forms/:id/edittag' => 'forms#edittag'
  get 'forms/bookmarks' => 'forms#bookmarks'     
  get '/trending' =>  'static_pages#trending'
  get '/most_viewed' =>  'static_pages#most_viewed'
  get '/most_liked' =>  'static_pages#most_liked'
  get '/most_recent' =>  'static_pages#most_recent'
  get '/most_shared' =>  'static_pages#most_shared'
  get '/most_saved' =>  'static_pages#most_saved'
  get '/staff_picks' =>  'static_pages#staff_picks'
  get '/most_popular' =>  'static_pages#most_popular'
  get '/dashboard' => 'static_pages#dashboard'
  
  get ':id/published'          =>   'users#show'
  get ':id/saved'          =>   'users#show_saved'
  get ':id/drafts'          =>   'users#show_drafts'

  get ':id/liked'          =>   'users#show_liked'
  get 'user/:id/followings' => 'users#followings'
  get 'user/:id/followers' => 'users#followers'
  
  get '/user_admin' => 'users#user_for_admin'
  post '/user_admin' => 'users#user_create_for_admin'

  get '/mixpanel_data' => 'forms#mixpanel_data'
  get '/update_all_forms' => 'forms#update_all_forms'
  post '/update_form_list' => 'forms#update_form_list'
  post '/update_form_admin' => 'forms#update_form_admin'
  delete '/delete_form' => 'forms#delete_form'

  get '/get_trending_board_data' => 'forms#get_trending_board_data'
  post '/update_form_score' => 'forms#update_form_score'

  get '/:id/:slug_url' => 'forms#show'

  root 'static_pages#home'
   
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_admin, :only => [:dashboard]
  # before_filter :authenticate_user, :only => [:home]
  #before_action :set_boards, only: [:trending, :most_recent, :most_liked, :most_viewed]
  
  def get_customized_forms(forms)
    forms.map {|f| {secure_id: f.secure_id, form_url: "#{root_url}#{f.user.username}/#{f.slug_url}", slug_url: f.slug_url, id: f.id, title: f.title,liked:f.votes.map{|v| v.voter_id}.include?(current_user.id), bookmark: f.user_form_bookmarks.map{|u| u.user_id}.include?(current_user.id) ,sub_header: f.sub_header ,dsc: f.description, likes: f.cached_votes_total ,updated_at: f.order_date ,user: f.user,user_image: (f.user.avatar_file_name == nil ? nil : f.user.avatar(:thumb)) ,links: 
      [{url: f.url1, title: f.title1, dsc: f.description1, image: f.image1, note: f.note1, host: f.host1 },
      {url: f.url2, title: f.title2, dsc: f.description2, image: f.image2, note: f.note2, host: f.host2 },
      {url: f.url3, title: f.title3, dsc: f.description3, image: f.image3, note: f.note3, host: f.host3 },
      {url: f.url4, title: f.titel4, dsc: f.description4, image: f.image4, note: f.note4, host: f.host4 },
      {url: f.url5, title: f.title5, dsc: f.description5, image: f.image5, note: f.note5, host: f.host5 }]}}
  end

  def get_uniq_forms_from_category(category, ids)
    @forms_uniq_ids = ids
    if @forms_uniq_ids == []
      forms = Form.tagged_with("cat_#{category.downcase.split(' ').join('_')}").includes(:user, :user_form_bookmarks, :votes).order(order_date: :desc).published.limit(3)
      @forms_uniq_ids = forms.pluck(:id)
      return forms
    else
      forms = Form.tagged_with("cat_#{category.downcase.split(' ').join('_')}").includes(:user, :user_form_bookmarks, :votes).where.not(id: @forms_uniq_ids).order(order_date: :desc).published.limit(3)
      @forms_uniq_ids = @forms_uniq_ids + forms.pluck(:id)
      return forms
    end
  end

  def home #home.html.erb    
    @home_user = true;
    @keys = ENV['FACEBOOK_KEY'].to_json
    if current_user
      puts current_user.profile_completed
      if current_user.profile_completed
        @cat_boards = []
        @forms_uniq_ids = []      

        staff_pick = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("s_b").form_ids).order(order_date: :desc).published.sample(3)
        staff_pick_hash = { category: "staff_picks", name: "staff picks", boards: get_customized_forms(staff_pick)}
        @cat_boards.push staff_pick_hash

        form_ids = AllForm.find_by_forms_type("t_b").form_ids
        forms_ids = Form.includes(:user, :user_form_bookmarks, :votes).where(id: form_ids).published.index_by(&:id)
        trending = form_ids.collect {|id| forms_ids[id] }[0..2]      
        trend_hash = { category: "trending", name: "trending", boards: get_customized_forms(trending)}

        categories = current_user.categories_ids.reject { |c| c.empty? }      
        categories.each_with_index do |category, index|
          next if index > 2
          cat_hash = { category: category.downcase.split(" ").join("_"), name: category, boards: [] }
          forms = get_uniq_forms_from_category(category, @forms_uniq_ids)
          cat_hash[:boards] = get_customized_forms(forms)
          if index == 1
            @cat_boards.push trend_hash  
          end
          @cat_boards.push cat_hash
        end
      else
        redirect_to edit_user_path(current_user)
      end

      # TODO: Fetch categories_ids
      @formss = @cat_boards.to_json
    else
      @skip_header = true;
    end
  end

  def categories
    @home_user = true;
    @cat_name = "cat_" + params[:name].downcase
    @keys = ENV['FACEBOOK_KEY'].to_json
    if Category.pluck(:tag).include?(@cat_name)
      @forms = Form.tagged_with("#{@cat_name}").includes(:user, :user_form_bookmarks, :votes).order(order_date: :desc).published
      if current_user
        @boards = @forms.map {|f| {secure_id: f.secure_id, form_url: "#{root_url}#{f.user.username}/#{f.slug_url}", slug_url: f.slug_url, id: f.id, title: f.title,liked:f.votes.map{|v| v.voter_id}.include?(current_user.id), bookmark: f.user_form_bookmarks.map{|u| u.user_id}.include?(current_user.id) ,sub_header: f.sub_header ,dsc: f.description, likes: f.cached_votes_total ,updated_at: f.order_date ,user: f.user,user_image: (f.user.avatar_file_name == nil ? nil : f.user.avatar(:thumb)) ,links: 
      [{url: f.url1, title: f.title1, dsc: f.description1, image: f.image1, note: f.note1, host: f.host1 },
      {url: f.url2, title: f.title2, dsc: f.description2, image: f.image2, note: f.note2, host: f.host2 },
      {url: f.url3, title: f.title3, dsc: f.description3, image: f.image3, note: f.note3, host: f.host3 },
      {url: f.url4, title: f.titel4, dsc: f.description4, image: f.image4, note: f.note4, host: f.host4 },
      {url: f.url5, title: f.title5, dsc: f.description5, image: f.image5, note: f.note5, host: f.host5 }]}}
      else
        redirect_to root_url  
      end
    else
      redirect_to root_url
    end
    @formss = @boards.to_json
  end

  def get_boards(forms)
    forms.map {|f| {secure_id: f.secure_id, form_url: "#{root_url}#{f.user.username}/#{f.slug_url}", slug_url: f.slug_url, id: f.id, title: f.title,liked: f.votes.map{|v| v.voter_id}.include?(current_user.id), bookmark: f.user_form_bookmarks.map{|u| u.user_id}.include?(current_user.id) ,sub_header: f.sub_header ,dsc: f.description, likes: f.cached_votes_total ,updated_at: f.order_date ,user: f.user,user_image: (f.user.avatar_file_name == nil ? nil : f.user.avatar(:thumb)) ,links: 
      [{url: f.url1, title: f.title1, dsc: f.description1, image: f.image1, note: f.note1, host: f.host1 },
      {url: f.url2, title: f.title2, dsc: f.description2, image: f.image2, note: f.note2, host: f.host2 },
      {url: f.url3, title: f.title3, dsc: f.description3, image: f.image3, note: f.note3, host: f.host3 },
      {url: f.url4, title: f.titel4, dsc: f.description4, image: f.image4, note: f.note4, host: f.host4 },
      {url: f.url5, title: f.title5, dsc: f.description5, image: f.image5, note: f.note5, host: f.host5 }]}}
  end

  def trending
    @keys = ENV['FACEBOOK_KEY'].to_json
    form_ids = AllForm.find_by_forms_type("t_b").form_ids    
    forms_ids = Form.includes(:user, :user_form_bookmarks, :votes).where(id: form_ids).published.index_by(&:id)    
    @forms = form_ids.collect {|id| forms_ids[id] }    
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end

  def most_viewed
    @keys = ENV['FACEBOOK_KEY'].to_json
    @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("m_v_b").form_ids).published
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end

  def most_liked
    @keys = ENV['FACEBOOK_KEY'].to_json
    @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("m_l_b").form_ids).published
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end

  def most_recent
    @keys = ENV['FACEBOOK_KEY'].to_json
    @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("m_r_b").form_ids).order(order_date: :desc).published
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end

  def most_shared
    @keys = ENV['FACEBOOK_KEY'].to_json
    @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("m_sh_b").form_ids).published
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end

  def most_saved
    @keys = ENV['FACEBOOK_KEY'].to_json
    @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("m_sa_b").form_ids).published
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end

  def most_popular
    @keys = ENV['FACEBOOK_KEY'].to_json
    @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("m_l_b").form_ids).published
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end
  
  def staff_picks
    @keys = ENV['FACEBOOK_KEY'].to_json
    @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: AllForm.find_by_forms_type("s_b").form_ids).order(order_date: :desc).published
    @boards = get_boards(@forms)
    @formss = @boards.to_json
  end

  def destroy #to delete the form
   @form.destroy
   respond_to do |format|
    format.html { redirect_to root_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update 
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
  end

  # def saved #saved.html.erb
  #  @home_user = true;   #board validation for showing things and to not show somethings
  #  @home_user1 = true;
  #  @forms = Form.where(bookmark:true).order(created_at: :desc) #id: current_user.find_voted_items means it shows current_users liked boards. find_voted_item is a predefined function by acts_as_votable.
  # end    
 
  def dashboard
  end
  
  private

  def authenticate_admin
    authenticate_admin!
  end

  def authenticate_user
    authenticate_user!
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_boards.html.erb
<%# Please make sure to update 'forms/social_image.html.erb' file if this file is updated %>

<div class="" ng-controller="AppCtrl" ng-init='init(<%= @formss %>, <%= @keys %>)'>
 
    <div class="boardContainer" ng-repeat="cat_board in cat_boards">
      <div class="">
        <div class="categoryheader">
          <div class="categorytitle col-md-8" >
            <span>
              <a ng-if="cat_board.category != 'trending' && cat_board.category != 'staff_picks' " ng-href="/categories/{{cat_board.category}}">
                {{cat_board.name}}
              </a>

              <a ng-if="(cat_board.category == 'trending' || cat_board.category == 'staff_picks')" ng-href="/{{cat_board.category}}">
                {{cat_board.name}}
              </a>
            </span>
          </div>
          <div class="categorytitle col-md-4">
            
            <a ng-if="cat_board.category != 'trending' && cat_board.category != 'staff_picks' " ng-href="/categories/{{cat_board.category}}">
              <i class="material-icons">keyboard_arrow_right</i>  
            </a>

            <a ng-if="(cat_board.category == 'trending' || cat_board.category == 'staff_picks')" ng-href="/{{cat_board.category}}">
              <i class="material-icons">keyboard_arrow_right</i>
            </a>
          
          </div>
          <hr>
        </div>

      <section class="cards" layout="row" layout-wrap>  
        <div class ="repeatBoard" ng-repeat="board in cat_board.boards"  ng-init="outerIndex=$index; boardsLength=category_boards.length" ng-class="(boardsLength%3 != 0 && (boardsLength-1) == outerIndex) ? 'fullBoard' : ((outerIndex%3 == 0) ? 'fullBoard' : 'halfBoard')">
          <%= render 'static_pages/board'%>  
        </div>
      </section>  
      </div>
      <br>
    </div>

</div>

app/views/static_pages/_cat_boards.html.erb
<%# Please make sure to update 'forms/social_image.html.erb' file if this file is updated %>

<div class="boardContainer" ng-controller="AppCtrl" ng-init="init(<%= @formss %>, <%= @keys %>)">
    
  <section class="cards" layout="row" layout-wrap>
    <div class ="repeatBoard" ng-repeat="board in category_boards"  ng-init="outerIndex=$index; boardsLength=category_boards.length" ng-class="(boardsLength%3 != 0 && (boardsLength-1) == outerIndex) ? 'fullBoard' : ((outerIndex%3 == 0) ? 'fullBoard' : 'halfBoard')">

      <%= render 'static_pages/board'%>
      
    </div>
  </section>
</div>

app/views/static_pages/_footer.html.erb
<div class="footer-section">
	<md-divider></md-divider>

	<div style="margin: auto; width: 75%">
		<section class="">
    	<div class="categoryheader">
    		<div class="categorytitle">
    			<span>Discover More</span>
    		</div>
    	</div>
  	</section>
 		<div layout="row" layout-padding layout-wrap layout-fill style="padding-bottom: 32px;" ng-cloak layout layout-align="center center">

			<% category_list = Category.all.order(:rank).pluck(:category_name) %>
			<% user_category_list = current_user.categories_ids.reject { |c| c.empty? } %>
			<% remove_3_category = user_category_list.drop(3) %>
			<% new_category_list = (category_list - user_category_list) %>
			<% whiteframe = (remove_3_category + new_category_list).each_with_index do |f,index| %>
				<% next if index > 5 %>
				<md-whiteframe class="md-whiteframe-3dp" flex-sm="45" flex-gt-sm="35" flex-gt-md="20" layout layout-align="center center">
			    	<a style="" layout="row" layout layout-align="center center" href='/categories/<%= f.split(' ').join('_').downcase %>'>
			    		<span style="text-align:center;"><%= f %></span>
			  		</a>
			  	</md-whiteframe>
			<% end %>

			<md-whiteframe class="md-whiteframe-3dp" flex-sm="45" flex-gt-sm="35" flex-gt-md="20" layout layout-align="center center">
			  <a style="" layout="row" layout layout-align="center center" href="/most_recent">
			    <span>Most Recent</span>
			  </a>
			</md-whiteframe>

			<md-whiteframe class="md-whiteframe-3dp" flex-sm="45" flex-gt-sm="35" flex-gt-md="20" layout layout-align="center center">
			<a style="" layout="row" layout layout-align="center center" href="/most_popular">
				<span>Most Popular</span>
				</a>
			</md-whiteframe>

			<% if whiteframe.first(5).include?("Unconventional Views") || user_category_list.first(3).include?("Unconventional Views")  %>
				<md-whiteframe class="md-whiteframe-3dp" flex-sm="45" flex-gt-sm="35" flex-gt-md="20" layout layout-align="center center">
					<a style="" layout="row" layout layout-align="center center" href="/most_saved">
						<span>Most Saved</span>
					</a>
				</md-whiteframe>
			<% else %>
				<md-whiteframe class="md-whiteframe-3dp" flex-sm="45" flex-gt-sm="35" flex-gt-md="20" layout layout-align="center center">
					<a style="" layout="row" layout layout-align="center center" href="/categories/unconventional_views">
						<span>Unconventional Views</span>
					</a>
				</md-whiteframe>
			<% end %>

		</div>
	</div>
</div>

app/views/static_pages/_home_boards.html.erb
<%# Please make sure to update 'forms/social_image.html.erb' file if this file is updated %>

<div class="boardContainer" ng-controller="HomeAppCtrl" ng-init="init(<%= @formss %>)">
    <div ng-repeat="board in boards" ng-init="outerIndex=$index; boardsLength=category_boards.length" ng-class="(boardsLength%3 != 0 && (boardsLength-1) == outerIndex) ? 'fullBoard' : ((outerIndex%3 == 0) ? 'fullBoard' : 'halfBoard')">
      <%= render 'static_pages/board'%>
    </div>
</div>

app/views/static_pages/_saved_boards.html.erb
<%# Please make sure to update 'forms/social_image.html.erb' file if this file is updated %>

<div class="boardContainer" ng-controller="SavedBoardCtrl" ng-init="init(<%= @saved_boards %>)">
  <div>
    <section class="cards" layout="row" layout-wrap>   
      <div class ="repeatBoard" ng-repeat="board in saved_boards" ng-init="outerIndex=$index; boardsLength=saved_boards.length" ng-class="(boardsLength%3 != 0 && (boardsLength-1) == outerIndex) ? 'fullBoard' : ((outerIndex%3 == 0) ? 'fullBoard' : 'halfBoard')">
        <%= render 'static_pages/board'%>
      </div>
    </section>
  </div>
</div>

app/views/static_pages/dashboard.html.erb
<md-content flex>
	<br>
	<br>
	<br>
	<br>
	<h1>Dashboard</h1>
	<a href="/admin_forms">New forms data</a>
	<br>
	<br>	
	<%= link_to 'Categories', categories_path %>
	<br>
	<br>
	<%= link_to 'Users', users_path %>
	<br>
	<br>
	<a href="/user_admin">Create Dummy Users</a>
	<br>
	<br>
	<a href="/mixpanel_data">Mixpanel Data</a>
	<br>
	<br>
	<a href="/update_all_forms">Update Form List</a>
	<br>
	<br>	
</md-content>

app/views/static_pages/home.html.erb
<!-- if user has signed in -->
<% if user = current_user %>
<md-content flex>
  <%= render 'static_pages/boards'%>
  <br>
  <%= render 'static_pages/footer' %>
</md-content>
  <script type="text/javascript">
    mixpanel.track("Page Viewed", {
      "Page Name": 'Home Page',
      "Username": '<%= current_user.username %>'    
    });
  </script>
  <% if request.referrer == edit_user_url(user) %>
    <script type="text/javascript">
      mixpanel.alias('<%= current_user.username %>');      
      mixpanel.people.set({
        "$first_name": '<%= current_user.name %>',
        "$created": '<%= current_user.created_at %>',
        "$email": '<%= current_user.email %>'
      });            
      mixpanel.track("Sign Up Completed", {
        "Username": '<%= current_user.username %>',
        "Authentication Method": '<%= current_user.provider %>',
        "email": '<%= current_user.email %>'
      });
    </script>
    <script type="text/javascript">
      mixpanel.identify('<%= current_user.username %>');
      mixpanel.track("Sign In", {
        "Username": '<%= current_user.username %>',
        "Authentication Method": '<%= current_user.provider %>',
        "First Sign-in": '<%= current_user.created_at.to_date %>',
        "Last Sign-in": '<%= current_user.last_sign_in_at.to_date %>',
        "# of Sign-ins": '<%= current_user.sign_in_count %>'
      });
    </script>
  <% end %>
  <% if request.referrer == root_url %>
    <script type="text/javascript">
      mixpanel.identify('<%= current_user.username %>');
      mixpanel.track("Sign In", {
        "Username": '<%= current_user.username %>',
        "Authentication Method": '<%= current_user.provider %>',
        "First Sign-in": '<%= current_user.created_at.to_date %>',
        "Last Sign-in": '<%= current_user.last_sign_in_at.to_date %>',
        "# of Sign-ins": '<%= current_user.sign_in_count %>'
      });
    </script>
  <% end %>

<!-- if user isn't signed in -->
<% else %>
<div id="showModal" ng-controller="RegistrationsCtrl" ng-init="init()"></div>

<br>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-xs-3 hidden-md hidden-lg"></div>
  <div class="col-md-6 col-xs-6">

    <div id="image-center">
      <%= image_tag 'https://s3.us-east-2.amazonaws.com/thecurativ-master/thecurativ-logo-center.svg', id:"before-signup-logo" %>
    </div>
    <!-- <div class="col-xs-1 visible-sm">
      <%= link_to 'Sign In/Up', new_user_session_path, remote:true %>
    </div> -->
  </div>

  <div class="col-md-3 col-xs-3">
    <br>
    <%= link_to 'Sign In/Up', new_user_session_path, remote:true, id:"signinup" %>
  </div>
</div>

<br class="hidden-md hidden-lg">
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <p class="before-signup-text">Aggregate, Discover & Share <br> truly great media & content on the web.</p>  
  </div>
  <div class="col-md-3"></div>
</div>
<br>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= image_tag 'Screen Shot 2017-09-23 at 4.48.57 PM.png', id:"screenshot" %>
  </div>
  <div class="col-md-3"></div>
</div>
<br><br>
<div class="row picks">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="col-md-1"></div>
    <div class="col-md-2 col-xs-3">Pick a <br><b>TOPIC</b></div>
    <div class="col-md-2 col-xs-2"><%= image_tag 'Arrow 29 (1).svg', id:"arrows" %></div>
    <div class="col-md-2 col-xs-3">Choose <br><b>5 LINKS</b></div>
    <div class="col-md-2 col-xs-2"><%= image_tag 'Arrow 29 (1).svg', id:"arrows" %></div>
    <div class="col-md-2 col-xs-2">Publish <br><b>& Share</b></div>
    <div class="col-md-1"></div>
  </div>
  <div class="col-md-3"></div>
</div>
<br><br>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <hr style="border:1px solid #9c1717;">
    <p class="before-signup-footer">tell a STORY &nbsp;&nbsp; |&nbsp;&nbsp; explain TOPIC &nbsp;&nbsp; |&nbsp;&nbsp; express a VIEW &nbsp;&nbsp;|&nbsp;&nbsp; build a COLLECTION &nbsp;&nbsp;|&nbsp;&nbsp; keep LEARNING</p>
  </div>
  <div class="col-md-1"></div>
</div>
<script type="text/javascript">
  mixpanel.track("Page Viewed", {
    "Page Name": 'Landing Page',    
  });
</script>

<% end %>


<style type="text/css">
  html
  {
    overflow-x:hidden;
  }

</style>

app/views/static_pages/most_liked.html.erb
<md-content flex>
	<div class="categoryheader">
	  <h2>Most Liked</h2>
	</div>
<%= render 'static_pages/cat_boards'%>
<script type="text/javascript">
    mixpanel.track("Page Viewed", {
      "Page Name": 'Most Liked',
      "Username": '<%= current_user.username %>'    
    });
</script>

</md-content>

app/views/static_pages/most_recent.html.erb
<md-content flex>
	<div class="categoryheader">
	  <h2>Most Recent</h2>
	</div>
<%= render 'static_pages/cat_boards'%>
<script type="text/javascript">
    mixpanel.track("Page Viewed", {
      "Page Name": 'Most Recent',
      "Username": '<%= current_user.username %>'    
    });
</script>

</md-content>

app/views/static_pages/most_shared.html.erb
<md-content flex>
	<div class="categoryheader">
	  <h2>Most Shared</h2>
	</div>
<%= render 'static_pages/cat_boards'%>
<script type="text/javascript">
    mixpanel.track("Page Viewed", {
      "Page Name": 'Most Shared',
      "Username": '<%= current_user.username %>'    
    });
</script>

</md-content>

app/views/static_pages/most_viewed.html.erb
<md-content flex>
	<div class="categoryheader">
	  <h2>Most Viewed</h2>
	</div>
<%= render 'static_pages/cat_boards'%>

<script type="text/javascript">
    mixpanel.track("Most Viewed", {
      "Page Name": 'Home Page',
      "Username": '<%= current_user.username %>'    
    });
</script>

</md-content>

app/views/static_pages/staff_picks.html.erb
<md-content flex>
	<div class="categoryheader">
	  <h2>Staff Picks</h2>
	</div>
<%= render 'static_pages/cat_boards'%>
	
	<script type="text/javascript">
	    mixpanel.track("Page Viewed", {
	      "Page Name": 'Staff Pick',
	      "Username": '<%= current_user.username %>'    
	    });
	  </script>

</md-content>