config/routes.rb
Rails.application.routes.draw do
  

   devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  

  
  get 'users/index'
  get 'tags/:tag', to: 'forms#tagss', as: :tag 
 

  devise_for :users, :controllers => { sessions: "users/sessions", :registrations => 'users/registrations',
                                       :confirmations => 'users/confirmations', :passwords => 'users/passwords', omniauth_callbacks: "users/omniauth_callbacks"}

  resources :user_steps

  get '/:id/new_form' => 'forms#new_modal'
  get '/:id/:slug_url/edit_form' => 'forms#edit_modal'
  get '/:id/:slug_url/get_form_data' => 'forms#get_form_data'
  post '/:id/:slug_url/update_form' => 'forms#update_form'
  get '/:id/:slug_url/get_meta_data' => 'forms#get_meta_data'
  get '/:id/get_meta_data' => 'forms#get_meta_data'
  post '/:id/create_form' => 'forms#create_form'

  get '/users/categories' => 'users#categories'
  post '/users/update_categories' => 'users#update_categories'  
  
  get '/admin_forms' => 'forms#admin_index'
  get '/get_forms' => 'forms#get_admin_forms'
  resources :forms, :only => [:index, :edit, :update, :destroy] do
    member do
      get "like"
      get "unlike"
      get "book"
      get "booknot"
      put "difficulty", to: "forms#difficulty"
    end
  end

  resources :users, :only => [:index, :show, :edit, :update] do
    member do
      get 'categories' => 'users#categories'
      post 'update_categories' => 'users#update_categories'
      post 'link_clicked' => 'users#link_clicked' 
    end
    resources :follows, :only => [:create, :destroy]
  end

  resources :profile_validation, only: [:index]
  
  resources :categories, :only => [:index, :new, :create, :update, :destroy, :edit]
  get '/categories/:name' => 'static_pages#categories'

  get '/following' => 'follows#following'
  get '/followers' => 'follows#followers'

  resources :follows, :only => [:create, :destroy]

  get '/forms/:id/edittag' => 'forms#edittag'
  get 'forms/bookmarks' => 'forms#bookmarks'     
  get '/trending' =>  'static_pages#trending'
  get '/most_viewed' =>  'static_pages#most_viewed'
  get '/most_liked' =>  'static_pages#most_liked'
  get '/most_recent' =>  'static_pages#most_recent'
  get '/most_shared' =>  'static_pages#most_shared'
  get '/most_saved' =>  'static_pages#most_saved'
  get '/staff_picks' =>  'static_pages#staff_picks'
  get '/most_popular' =>  'static_pages#most_popular'
  get '/dashboard' => 'static_pages#dashboard'
  
  get ':id/published'          =>   'users#show'
  get ':id/saved'          =>   'users#show_saved'
  get ':id/drafts'          =>   'users#show_drafts'

  get ':id/liked'          =>   'users#show_liked'
  get 'user/:id/followings' => 'users#followings'
  get 'user/:id/followers' => 'users#followers'
  
  get '/user_admin' => 'users#user_for_admin'
  post '/user_admin' => 'users#user_create_for_admin'

  get '/mixpanel_data' => 'forms#mixpanel_data'
  get '/update_all_forms' => 'forms#update_all_forms'
  post '/update_form_list' => 'forms#update_form_list'
  post '/update_form_admin' => 'forms#update_form_admin'
  delete '/delete_form' => 'forms#delete_form'

  get '/get_trending_board_data' => 'forms#get_trending_board_data'
  post '/update_form_score' => 'forms#update_form_score'

  get '/:id/:slug_url' => 'forms#show'

  root 'static_pages#home'
   
  

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:edit, :update, :destroy, :like, :unlike, :book, :booknot]
  before_action :authenticate_user!, :only => [:like]
  respond_to :js, :json, :html
  before_filter :authenticate_admin, :only => [:index, :mixpanel_data, :update_all_forms, :admin_index, :get_admin_forms, :update_form_admin, :delete_form]
  
  # GET /forms
  # GET /forms.json
  def index #index.html.erb
    @forms = Form.order(created_at: :desc).all
    #index is method where you get a list of all the forms avaliable in your database. In this they are showing all the published forms. We have set the value of publish to be true so its shows all the published forms
      @form = Form.find(params[:format]) rescue nil
      if params[:commit] == 'Publish'         # it checks if the user has clicked publish the it updates the form with publish
        @form.record_timestamps=false
        @form.update_attributes(form_params)      #publish becomes true
        redirect_to :back
      end
    end

  def admin_index
    #@forms = Form.order(created_at: :desc).all
  end

  def get_admin_forms
    forms = Form.order(created_at: :desc).all.includes(:user)

    @forms_list = forms.map {|f| {id: f.id, title: f.title, username: f.user.username, created_at: f.created_at.in_time_zone(TZInfo::Timezone.get('Asia/Kolkata')).strftime("%d/%m/%Y %H:%M:%S%p"), updated_at: f.updated_at.in_time_zone(TZInfo::Timezone.get('Asia/Kolkata')).strftime("%d/%m/%Y %H:%M:%S%p"), admins_date: f.admins_date.present? ? f.admins_date.in_time_zone(TZInfo::Timezone.get('Asia/Kolkata')).strftime("%d/%m/%Y %H:%M:%S%p") : "-",
      title1: f.title1, host1: f.host1, title2: f.title2, host2: f.host2,
      title3: f.title3, host3: f.host3, title4: f.titel4, host4: f.host4,
      title5: f.title5, host5: f.host5, tags: f.tag_list.map {|tag| {:text => tag}}, admin_date: nil, staff_picks: f.staff_picks, 
      most_popular: f.most_popular, view_count: f.view_count, share_count: f.share_count, saved_count: f.saved_count, users: (f.user.email == current_admin.email) ? (User.where("email LIKE ?", "%@curativ.com%").map{ |cur| cur.username }) : "", selected_user: '', admin_date_to_update: f.admins_date.present? ? (f.admins_date.to_f * 1000) : nil}}
    respond_to do |format|
        format.html
        format.json { render json: @forms_list.to_json }
      end
  end

  def update_form_admin
    form = Form.find(params[:form]["id"])
    selected_user = params[:form]["selected_user"]    
    user_id = (selected_user == "None" || selected_user == "") ? form.user_id : User.find_by_username(params[:form]["selected_user"]).id    
    if form
      form.record_timestamps=false
      form.update_attributes(:staff_picks => params[:form]["staff_picks"], :most_popular => params[:form]["most_popular"], :view_count => params[:form]["view_count"], :share_count => params[:form]["share_count"], :saved_count => params[:form]["saved_count"],
        :tag_list => params[:form]["tags"].present? ? params[:form]["tags"].map{|aa| aa.values.join(",")}.join(",") : "", :user_id => user_id, :admins_date => params[:form]["date"].present? ? Time.at( params[:form]["date"] / 1000.0 ) : nil, :order_date => params[:form]["date"].present? ? Time.at( params[:form]["date"] / 1000.0 ) : form.created_at)
      respond_to do |format|
        format.html
        format.json { render json: {data: "OK".to_json } }
      end
    else
      respond_to do |format|
        format.html
        format.json { render json: {data: "FAILED".to_json } }
      end
    end
  end

  def update_list
    trending_list = []
    staff_picks_list = []
    most_viewed = []
    most_saved = []
    most_liked = []
    most_recent = []
    most_shared = []
    most_popular = []
    all_forms = Form.published
    trending_list = all_forms.order('score + extra_weight DESC').limit(10).pluck(:id)
    staff_picks_list = all_forms.where(staff_picks: true).order(order_date: :desc).limit(10).pluck(:id)
    most_viewed = all_forms.order(view_count: :desc).limit(10).pluck(:id)
    most_saved = all_forms.order(saved_count: :desc).limit(10).pluck(:id)
    most_liked = all_forms.where("cached_votes_total > ?", 0).order(cached_votes_total: :desc).limit(10).pluck(:id)
    most_recent = all_forms.order(order_date: :desc).limit(10).pluck(:id)
    most_shared = all_forms.order(share_count: :desc).limit(10).pluck(:id)
    most_popular = all_forms.where(most_popular:true).limit(10).pluck(:id)

    list = { 1 => { "form_ids" => trending_list }, 2 => { "form_ids" => staff_picks_list }, 3 => { "form_ids" => most_viewed }, 
    4 => { "form_ids" => most_saved }, 5 => { "form_ids" => most_liked }, 6 => { "form_ids" => most_recent }, 7 => { "form_ids" => most_shared }, 8 => { "form_ids" => most_popular } }
    form_list = AllForm.update(list.keys, list.values)
  end

  def delete_form
    form = Form.find(params[:form_id])
    form.destroy
    update_list
    respond_to do |format|
      format.html
      format.json { render json: "Deleted" }
    end
  end

  def get_boards(forms)
    forms.map {|f| {secure_id: f.secure_id, form_url: "#{root_url}#{f.user.username}/#{f.slug_url}", slug_url: f.slug_url, id: f.id, title: f.title,liked:f.votes.map{|v| v.voter_id}.include?(current_user.id), bookmark: f.user_form_bookmarks.map{|u| u.user_id}.include?(current_user.id) ,sub_header: f.sub_header ,dsc: f.description, likes: f.cached_votes_total ,updated_at: f.order_date ,user: f.user,user_image: (f.user.avatar_file_name == nil ? nil : f.user.avatar(:thumb)) ,links: 
      [{url: f.url1, title: f.title1, dsc: f.description1, image: f.image1, note: f.note1, host: f.host1 },
      {url: f.url2, title: f.title2, dsc: f.description2, image: f.image2, note: f.note2, host: f.host2 },
      {url: f.url3, title: f.title3, dsc: f.description3, image: f.image3, note: f.note3, host: f.host3 },
      {url: f.url4, title: f.titel4, dsc: f.description4, image: f.image4, note: f.note4, host: f.host4 },
      {url: f.url5, title: f.title5, dsc: f.description5, image: f.image5, note: f.note5, host: f.host5 }]}}
  end
  
  # GET /forms/1
  # GET /forms/1.json
  def show    
    secure_id = params[:slug_url].split("-").last
    @form = Form.find_by_secure_id(secure_id)
    if @form.present?
      @form.punch(request)
      @forms = Form.includes(:user, :user_form_bookmarks, :votes).where(id: @form.id)
      @keys = ENV['FACEBOOK_KEY'].to_json
      if current_user
        #user_id value is current_user id shows the form created by a particular user. so if i click on robins form it shows my board.
        @boards = get_boards(@forms)    
      else
        @skip_header = true
        @boards = @forms.map {|f| {secure_id: f.secure_id, form_url: "#{root_url}#{f.user.username}/#{f.slug_url}", slug_url: f.slug_url, id: f.id, title: f.title,liked:true, bookmark: true ,sub_header: f.sub_header ,dsc: f.description, likes: f.cached_votes_total ,updated_at: f.order_date ,user: f.user,user_image: (f.user.avatar_file_name == nil ? nil : f.user.avatar(:thumb)) ,links: 
      [{url: f.url1, title: f.title1, dsc: f.description1, image: f.image1, note: f.note1, host: f.host1 },
      {url: f.url2, title: f.title2, dsc: f.description2, image: f.image2, note: f.note2, host: f.host2 },
      {url: f.url3, title: f.title3, dsc: f.description3, image: f.image3, note: f.note3, host: f.host3 },
      {url: f.url4, title: f.titel4, dsc: f.description4, image: f.image4, note: f.note4, host: f.host4 },
      {url: f.url5, title: f.title5, dsc: f.description5, image: f.image5, note: f.note5, host: f.host5 }]}}
      end   
      @pub_boards = @boards.to_json  
    else
      redirect_to "/"
    end
    
  end

  # GET /forms/new
  def new
    @form = Form.new 
    #this is new method. where you can create a new form. It is basically a form.
  end

  # GET /forms/1/edit
  def edit
    @edit_tag = true;
  end

  # POST /forms
  # POST /forms.json

  def generate_slug(form)
    @slug = "#{form.title.parameterize}"
    return @slug
  end

  def generate_secure_id(form)
    loop do
      @secure_id = SecureRandom.hex(6)
      break unless Form.where(secure_id: @secure_id).exists?
    end
    return @secure_id
  end

  def create
    @form = Form.new(form_params)  #Form.new shows the new form to the user
    if @form.save                  # if form.save means if it clicked on publish or draft
      
      @form.slug = generate_slug(@form)
      @form.secure_id = generate_secure_id(@form)
      @form.update_attributes(slug:@form.slug, secure_id:@form.secure_id)

      meta = MetaInspector.new(@form.url1, :allow_non_html_content => true) rescue nil #meta is variable where you input the url in the form and stores it. MetaInspector is a predefined class taken from metainspector gem which fetches all the url information
        if @form.url1.empty?
          @form.update_attributes(content:"", title1:"", image1:"", description1:"") rescue nil
        else
          @form.update_attributes(content:meta.content_type, title1:meta.title, image1:meta.images.best, description1:meta.description, tag1:meta.meta_tags["name"]["keywords"]) rescue nil
            if @form.content == "application/pdf" 
              @form.update_attributes(title1:"#{@form.content}")
            end
        end


      meta1 = MetaInspector.new(@form.url2, :allow_non_html_content => true)   rescue nil
      if @form.url2.empty?
          @form.update_attributes(content2:"", title2:"", image2:"", description2:"") rescue nil
        else
          @form.update_attributes(content2:meta1.content_type, title2:meta1.title, image2:meta1.images.best, description2:meta1.description, tag2:meta1.meta_tags["name"]["keywords"]) rescue nil
            if @form.content2 == "application/pdf" 
              @form.update_attributes(title2:"#{@form.content2}")
            end
        end     

      meta2 = MetaInspector.new(@form.url3, :allow_non_html_content => true) rescue nil
      if @form.url3.empty?

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_books.html.erb
<% if form.bookmark == true %>
  <%= link_to "", booknot_form_path(form.id), remote: true,
                        id: "book_#{form.id}",
                        class:"glyphicon glyphicon-bookmark" %>
<% else %>
  <%= link_to "", book_form_path(form.id), remote: true,
                        id: "book_#{form.id}",
                        class:"glyphicon glyphicon-bookmark empty" %>
<% end %>



<style type="text/css">
  .empty
  { 
  	color: white;
  	text-shadow: -1px 0 #9c1717, 0 1px #9c1717, 1px 0 #9c1717, 0 -1px #9c1717;
  }
</style>

app/views/forms/_follow_button.html.erb
<% if user_signed_in? %> 
<% unless @user == current_user %> 
    <% if current_user.following?(@user) %> 
        <%= button_to('Stop Following', follow_path(user, 
current_user.follow(@user).id), :method => :delete, :remote => true, 
class: 'btn btn-danger-outline') %> 
    <% else %> 
        <%= button_to('Follow', follows_path(@user), :remote => 
true, class: 'btn btn-success-outline') %> 
    <% end %> 
<% end %> 
<% end %> 

<% if user_signed_in? %>
  <div id="follow_user">
    <%= render :partial => "forms/follow_button", :locals => {:user => @user} %>
  </div>
 <%= current_user.follow_count %>
<% end %>

app/views/forms/_likes.html.erb
<% if current_user.liked?(form) %>
  <%= link_to "", unlike_form_path(form.id), remote: true,
                        id: "like_#{form.id}",
                        class:"glyphicon glyphicon-heart" %>
<% else %>
  <%= link_to "", like_form_path(form.id), remote: true,
                        id: "like_#{form.id}",
                        class:"glyphicon glyphicon-heart-empty" %>
<% end %>

app/views/forms/admin_index.html.erb
<div class="maincont" ng-controller="AdminFormListCtrl" ng-init="init()">    
  <style type="text/css">
    @keyframes spinner {
      to {transform: rotate(360deg);}
    }
     
    .spinner {
      content: '';
      box-sizing: border-box;
      position: absolute;
      top: 50%;
      left: 50%;
      width: 50px;
      height: 50px;
      margin-top: -20px;
      margin-left: -20px;
      border-radius: 50%;
      border: 2px solid #ccc;
      border-top-color: #333;
      animation: spinner .6s linear infinite;
    }
  </style>
  
  <table-responsive>
    <table>
      <div class ="table-condensed table-hover">
        <thead>
          <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Users Name</th>
            <th>Title 1 and Domain</th>
            <th>Title 2 and Domain</th>
            <th>Title 3 and Domain</th>
            <th>Title 4 and Domain</th>
            <th>Title 5 and Domain</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Admins Date</th>            
            <th>Curativ Accounts</th>
            <th>Tags</th>
            <th>Admins Date</th>
            <th>Staff Picks</th>
            <th>Most Popular</th>
            <th>View Count</th>
            <th>Shared Count</th>
            <th>Saved Count</th>            
            <th>Delete</th>            
          </tr>
        </thead>
        <tbody>
          <tr ng-if="loading_forms">
            <td colspan="22">
              <div style="height: 100px; width: 100%">
                <span class="spinner"></span>
              </div>
            </td>
          </tr>
          <tr ng-if="!loading_forms" ng-repeat="form in forms track by $index">
            <td>
              {{form.id}}
            </td>
            <td>
              {{form.title}}
            </td>
            <td>
              {{form.username}}
            </td>
            <td>
              {{form.title1}}
              <hr>
              {{form.host1}}
            </td>
            <td>
              {{form.title2}}
              <hr>
              {{form.host2}}
            </td>
            <td>
              {{form.title3}}
              <hr>
              {{form.host3}}
            </td>
            <td>
              {{form.title4}}
              <hr>
              {{form.host4}}
            </td>
            <td>
              {{form.title5}}
              <hr>
              {{form.host5}}
            </td>
            <td>
              {{form.created_at}}
            </td>
            <td>
              {{form.updated_at}}
            </td>
            <td>
              {{form.admins_date}}
            </td>
            <td>              
              <md-input-container ng-if="form.users.length > 0">
                <label>User</label>
                <md-select ng-model="form.selected_user" ng-change="change(form,$index)">
                  <md-option><em>None</em></md-option>                  
                  <md-option ng-repeat="user in form.users" ng-value="user">
                    {{user}}
                  </md-option>
                </md-select>
              </md-input-container>
            </td>
            <td>
              <div class="field">
                <tags-input row="3" id="textfield" ng-model="form.tags" placeholder="List upto 5 keywords, separated by commas,to help people to discover your board!" replace-spaces-with-dashes="false" on-tag-added="change(form,$index)" on-tag-removed="change(form,$index)">
                </tags-input>                
              </div>
            </td>
            <td>
               <md-datepicker name="date" ng-model="form.admin_date_to_update" ng-change="change(form, $index)" md-placeholder="Enter date" md-open-on-focus></md-datepicker>
            </td>
            <td>
              <md-checkbox ng-model="form.staff_picks" aria-label="Checkbox 1" ng-change="change(form, $index)"></md-checkbox>
            </td>
            <td><md-checkbox ng-model="form.most_popular" aria-label="Checkbox 1" ng-change="change(form, $index)"></md-checkbox></td>
            <td><input row="1" type="number" name="input" ng-model="form.view_count" ng-change="change(form, $index)"></input></td>
            <td><input row="1" type="number" name="input" ng-model="form.share_count" ng-change="change(form, $index)"></input></td>
            <td><input row="1" type="number" name="input" ng-model="form.saved_count" ng-change="change(form, $index)"></input></td>            
            <td>
              <md-button class="md-fab" aria-label="Eat cake" ng-confirm-click="Are you sure to delete this record ?" confirmed-click="remove(form, $index)">
                <md-icon><i class="material-icons">delete</i>
                </md-icon>
              </md-button>
            </td>            
          </tr>               
        </tbody>
      </div>
    </table>
<br>
</table-responsive>

</div>

<style type="text/css">
  #saves
  {
    width: 100%;
  }
</style>

app/views/forms/booknot.js.erb
$("#book_<%= @form.id %>").removeClass('glyphicon-bookmark').addClass('glyphicon-bookmark empty');
$("#book_<%= @form.id %>").attr("href", '/forms/<%= @form.id %>/book');
$("#books_<%= @form.id %>").html("<%= j (render partial: 'forms/books', locals: { form: @form } ) %>");

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form' %> 
<%-# To edit the form we use render function which shows us the form with its values in it. -%>

app/views/forms/index.html.erb
<div class="maincont" ng-controller="AdminFormListCtrl" ng-init="init()">
<table-responsive>
    <table>
        <div class ="table-condensed table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Users Name</th>
                    <th>Title 1 and Domain</th>
                    <th>Title 2 and Domain</th>
                    <th>Title 3 and Domain</th>
                    <th>Title 4 and Domain</th>
                    <th>Title 5 and Domain</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Admins Date</th>
                    <th>Tags</th>
                    <th>Curativ Accounts</th>
                    <th>Edit Tags</th>
                    <th>Admins Date</th>
                    <th>Staff Picks</th>
                    <th>Most Popular</th>
                    <th>View Count</th>
                    <th>Shared Count</th>
                    <th>Saved Count</th>
                    <th>Submit tag</th>
                    <!-- <th>Edit</th> -->
                    <th>Delete</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <% @forms.each do |form| %>
                    <% @userflname = form.user_id %>
                    <% @user = User.find(@userflname) %>
                    <td><%= form.id %></td>
                    <td><%= form.title %></td>
                    <td><%= @user.username %></td>
                    <td><%= form.title1 %> <hr> <%= form.url1.sub(/https?\:(\\\\|\/\/)(www.)?/,'').split('/').first %></td>
                    <td><%= form.title2 %> <hr> <%= form.url2.sub(/https?\:(\\\\|\/\/)(www.)?/,'').split('/').first %></td>
                    <td><%= form.title3 %> <hr> <%= form.url3.sub(/https?\:(\\\\|\/\/)(www.)?/,'').split('/').first %></td>
                    <td><%= form.titel4 %> <hr> <%= form.url4.sub(/https?\:(\\\\|\/\/)(www.)?/,'').split('/').first %></td>
                    <td><%= form.title5 %> <hr> <%= form.url5.sub(/https?\:(\\\\|\/\/)(www.)?/,'').split('/').first %></td>
                    <td><%= form.created_at.in_time_zone(TZInfo::Timezone.get('Asia/Kolkata')).strftime("%d/%m/%Y %H:%M:%S%p") %></td>
                    <td><%= form.updated_at.in_time_zone(TZInfo::Timezone.get('Asia/Kolkata')).strftime("%d/%m/%Y %H:%M:%S%p") %></td>
                    <td><%= form.admins_date.in_time_zone(TZInfo::Timezone.get('Asia/Kolkata')).strftime("%d/%m/%Y ") rescue nil %></td>
                    <td><%= form.tag_list %></td>
                    <td>
                      <%= form_for form, :url => forms_path(form), method: :get do |f| %>
                      <% if form.user.email == current_admin.email %>
                        <% @user_cur = User.where("email LIKE ?", "%@curativ.com%") %>
                        <%= f.select :user_id, options_for_select(@user_cur.map { |cur| [cur.username, cur.id] }) %>
                      <% end %>  
                    </td>
                    <td>
                        <!-- ROBIN, WE NEED TO ADD THESE FIELDS INTO THE DB -->
                        <div class="field">
                          <%= f.text_field :tag_list  , id:"textfield", rows:3 , placeholder:"List upto 5 keywords, separated by commas,to help people to discover your board!", 'data-role'=>'tagsinput', value:form.tag_list.to_s %>
                        </div>
                    </td>
                    <td>
                      <%= f.date_select :admins_date,  id:"notes", placeholder:"mm/dd/yyyy", value:form.admins_date %>
                    </td>
                    <td>
                      <%= f.text_field :staff_picks, placeholder:"Staff Picks", value:form.staff_picks %>
                    </td>
                    <td>
                      <%= f.text_field :most_popular, placeholder:"Most Popular", value:form.most_popular %>
                    </td>
                    <td>
                      <%= f.number_field :view_count,  id:"notes", placeholder:"View Count", value:form.view_count %>
                    </td>
                    <td>
                      <%= f.number_field :share_count,  id:"notes", placeholder:"Share Count", value:form.share_count %>
                    </td>
                    <td>
                      <%= f.number_field :saved_count,  id:"notes", placeholder:"Saved Count", value:form.saved_count %>
                    </td>    
                    <td>
                      <div class="actions">
                          <%= f.submit 'Publish', id:"saves", name:"commit"%>
                      </div>
                      <% end %>
                    </td>
                    <!-- <td><%= link_to 'Edit', edit_form_path(form) %></td> -->

                           
                    <td><%= link_to 'Delete', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <td></td>      
                </tr>   
                    <% end %>
            </tbody>
        </div>
    </table>
<br>
</table-responsive>

</div>

<style type="text/css">
    table
  {
   border: 1px solid pink;
   width: 80%;
  }

  td
  {
   border: 1px solid black;
   background-color: #D3D3D3;
  }

  th
  {
   background-color: white;
   border: 1px solid black;
  }

  #saves
  {
    width: 100%;
  }
</style>

app/views/forms/new.html.erb
<%= render 'form' %>

<!--<%= link_to 'Back', forms_path %>-->

app/views/forms/tagss.html.erb
<div class="maincont">
  <div id="forms">
	<%= render 'static_pages/boards'%>
  </div>
  <%= will_paginate @forms %>
</div>

app/views/forms/unlike.js.erb
$("#like_<%= @form.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @form.id %>").attr("href", '/forms/<%= @form.id %>/like');
$("#likes_<%= @form.id %>").html("<%= j (render partial: 'forms/likes', locals: { form: @form } ) %>");
$("#likes").html('<%= @form.get_likes.size %>');