config/routes.rb
Rails.application.routes.draw do
  

   devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  

  
  get 'users/index'
  get 'tags/:tag', to: 'forms#tagss', as: :tag 
 

  devise_for :users, :controllers => { sessions: "users/sessions", :registrations => 'users/registrations',
                                       :confirmations => 'users/confirmations', :passwords => 'users/passwords', omniauth_callbacks: "users/omniauth_callbacks"}

  resources :user_steps

  get '/:id/new_form' => 'forms#new_modal'
  get '/:id/:slug_url/edit_form' => 'forms#edit_modal'
  get '/:id/:slug_url/get_form_data' => 'forms#get_form_data'
  post '/:id/:slug_url/update_form' => 'forms#update_form'
  get '/:id/:slug_url/get_meta_data' => 'forms#get_meta_data'
  get '/:id/get_meta_data' => 'forms#get_meta_data'
  post '/:id/create_form' => 'forms#create_form'

  get '/users/categories' => 'users#categories'
  post '/users/update_categories' => 'users#update_categories'  
  
  get '/admin_forms' => 'forms#admin_index'
  get '/get_forms' => 'forms#get_admin_forms'
  resources :forms, :only => [:index, :edit, :update, :destroy] do
    member do
      get "like"
      get "unlike"
      get "book"
      get "booknot"
      put "difficulty", to: "forms#difficulty"
    end
  end

  resources :users, :only => [:index, :show, :edit, :update] do
    member do
      get 'categories' => 'users#categories'
      post 'update_categories' => 'users#update_categories'
      post 'link_clicked' => 'users#link_clicked' 
    end
    resources :follows, :only => [:create, :destroy]
  end

  resources :profile_validation, only: [:index]
  
  resources :categories, :only => [:index, :new, :create, :update, :destroy, :edit]
  get '/categories/:name' => 'static_pages#categories'

  get '/following' => 'follows#following'
  get '/followers' => 'follows#followers'

  resources :follows, :only => [:create, :destroy]

  get '/forms/:id/edittag' => 'forms#edittag'
  get 'forms/bookmarks' => 'forms#bookmarks'     
  get '/trending' =>  'static_pages#trending'
  get '/most_viewed' =>  'static_pages#most_viewed'
  get '/most_liked' =>  'static_pages#most_liked'
  get '/most_recent' =>  'static_pages#most_recent'
  get '/most_shared' =>  'static_pages#most_shared'
  get '/most_saved' =>  'static_pages#most_saved'
  get '/staff_picks' =>  'static_pages#staff_picks'
  get '/most_popular' =>  'static_pages#most_popular'
  get '/dashboard' => 'static_pages#dashboard'
  
  get ':id/published'          =>   'users#show'
  get ':id/saved'          =>   'users#show_saved'
  get ':id/drafts'          =>   'users#show_drafts'

  get ':id/liked'          =>   'users#show_liked'
  get 'user/:id/followings' => 'users#followings'
  get 'user/:id/followers' => 'users#followers'
  
  get '/user_admin' => 'users#user_for_admin'
  post '/user_admin' => 'users#user_create_for_admin'

  get '/mixpanel_data' => 'forms#mixpanel_data'
  get '/update_all_forms' => 'forms#update_all_forms'
  post '/update_form_list' => 'forms#update_form_list'
  post '/update_form_admin' => 'forms#update_form_admin'
  delete '/delete_form' => 'forms#delete_form'

  get '/get_trending_board_data' => 'forms#get_trending_board_data'
  post '/update_form_score' => 'forms#update_form_score'

  get '/:id/:slug_url' => 'forms#show'

  root 'static_pages#home'
   
  

end

app/views/layouts/_authendication_popover.html.erb
<div class="modal fade custom-modal" id="registrationModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span></button>
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content sign-in-with-email">
      <div class="modal-header">
        <!-- Header content for sign in with email -->
        <div class="sign-in-with-email">
          <div class="email-title">
            Enter your email address to sign in or create an account on Lense
          </div>
        </div>
      </div>
      <div class="modal-body">
        <div class="sign-up-title">
          Sign Up
        </div>
        <div class="sign-up-form" id="sign-up-form">
          <%= render partial: "users/registrations/sign_up_form" %>
        </div>
        <hr>
        <div class="sign-up-title m-t-30">
          Sign In
        </div>
        <div class="sign-up-form" id="sign-in-form">
          <%= render partial: "users/sessions/sign_in_form" %>
        </div>
        <div class="login-link">
          <a id="socialModal">Or sign in with Facebook, Twitter, or Google</a>
        </div>
      </div>
    </div>
    <div class="modal-content sign-in-with-social-media">
      <div class="modal-header">

        <div class="sign-in-title">
          THE LENSE
        </div>
      </div>
      <div class="modal-body">
        <div class="body-content">Sign in to Lense to connect with.</div>
        <div class="social-media-buttons">

          <%- if devise_mapping.omniauthable? %>
              <%- resource_class.omniauth_providers.each do |provider| %>
                  <%= link_to(omniauth_authorize_path(resource_name, provider)) do %>
                      <% if provider == :twitter %>
                          <button class="button button-with-icon twitter-button">
                            <div class="button-left-icon">
                              <svg class="svgIcon-use" width="25" height="25" viewBox="0 0 25 25">
                                <path d="M21.725 5.338c-.744.47-1.605.804-2.513 1.006a3.978 3.978 0 0 0-2.942-1.293c-2.22 0-4.02 1.81-4.02 4.02 0 .32.034.63.07.94-3.31-.18-6.27-1.78-8.255-4.23a4.544 4.544 0 0 0-.574 2.01c.04 1.43.74 2.66 1.8 3.38-.63-.01-1.25-.19-1.79-.5v.08c0 1.93 1.38 3.56 3.23 3.95-.34.07-.7.12-1.07.14-.25-.02-.5-.04-.72-.07.49 1.58 1.97 2.74 3.74 2.8a8.49 8.49 0 0 1-5.02 1.72c-.3-.03-.62-.04-.93-.07A11.447 11.447 0 0 0 8.88 21c7.386 0 11.43-6.13 11.414-11.414.015-.21.01-.38 0-.578a7.604 7.604 0 0 0 2.01-2.08 7.27 7.27 0 0 1-2.297.645 3.856 3.856 0 0 0 1.72-2.23"></path>
                              </svg>
                            </div>
                            <div class="button-right-content">
                              <span class="head-text">Continue with Twitter</span>
                              <span class="sub-text">We won’t post without asking</span>
                            </div>
                          </button>
                      <% end %>
                      <% if provider == :facebook %>
                          <button class="button button-with-icon facebook-button" href="<%= omniauth_authorize_path(resource_name, provider) %>">
                            <div class="button-left-icon">
                              <svg class="svgIcon-use" width="25" height="25" viewBox="0 0 25 25">
                                <path d="M21 12.646C21 7.65 16.97 3.6 12 3.6s-9 4.05-9 9.046a9.026 9.026 0 0 0 7.59 8.924v-6.376H8.395V12.64h2.193v-1.88c0-2.186 1.328-3.375 3.267-3.375.93 0 1.728.07 1.96.1V9.77H14.47c-1.055 0-1.26.503-1.26 1.242v1.63h2.517l-.33 2.554H13.21V21.6c4.398-.597 7.79-4.373 7.79-8.954"></path>
                              </svg>
                            </div>
                            <div class="button-right-content">
                              <span class="head-text">Continue with Facebook</span>
                              <span class="sub-text">We won’t post without asking</span>
                            </div>
                          </button>
                      <% end %>
                      <% if provider == :google_oauth2 %>
                          <button class="button button-with-icon google-button" href="<%= omniauth_authorize_path(resource_name, provider) %>">
                            <div class="button-left-icon">
                              <svg class="svgIcon-use" width="25" height="25" viewBox="0 0 25 25">
                                <g fill="none" fill-rule="evenodd">
                                  <path d="M20.66 12.693c0-.603-.054-1.182-.155-1.738H12.5v3.287h4.575a3.91 3.91 0 0 1-1.697 2.566v2.133h2.747c1.608-1.48 2.535-3.65 2.535-6.24z" fill="#4285F4"></path>
                                  <path d="M12.5 21c2.295 0 4.22-.76 5.625-2.06l-2.747-2.132c-.76.51-1.734.81-2.878.81-2.214 0-4.088-1.494-4.756-3.503h-2.84v2.202A8.498 8.498 0 0 0 12.5 21z" fill="#34A853"></path>
                                  <path d="M7.744 14.115c-.17-.51-.267-1.055-.267-1.615s.097-1.105.267-1.615V8.683h-2.84A8.488 8.488 0 0 0 4 12.5c0 1.372.328 2.67.904 3.817l2.84-2.202z" fill="#FBBC05"></path>
                                  <path d="M12.5 7.38c1.248 0 2.368.43 3.25 1.272l2.437-2.438C16.715 4.842 14.79 4 12.5 4a8.497 8.497 0 0 0-7.596 4.683l2.84 2.202c.668-2.01 2.542-3.504 4.756-3.504z" fill="#EA4335"></path>
                                </g>
                              </svg>
                            </div>
                            <div class="button-right-content">
                              <span class="head-text">Continue with Google</span>
                            </div>
                          </button>
                      <% end %>
                  <% end %>
              <% end -%>
          <% end -%>
        </div>
        <div class="login-link">
          <a id="emailModal">Sign in or sign up with email</a>
        </div>
        <!--<div class="content-footer">-->
        <!--<div>To use Medium you must have cookies enabled.</div>-->
        <!--<div>-->
        <!--If you sign up with Twitter or Facebook, we’ll start you off with a network by automatically importing any-->
        <!--followers/followees or friends already on Medium. Also, we’ll never post to Twitter or Facebook without your-->
        <!--permission. For more info, please see <a href="">Login FAQ</a>.-->
        <!--</div>-->
        <!--</div>-->
      </div>
    </div>
  </div>
</div>

<script>
    $( document ).ready(function() {
        $( "#emailModal" ).click(function() {
            $('.sign-in-with-social-media').hide();
            $('.sign-in-with-email').show();
        });
        $( "#socialModal" ).click(function() {
            $('.sign-in-with-social-media').show();
            $('.sign-in-with-email').hide();
        });
    });

</script>

app/views/layouts/_flash_alerts.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
    <%= flash[:error] %>
  </div>
<% end %>

<% if flash[:notice].present? %>
    <div class="alert alert-success alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
      <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:success].present? %>
    <div class="alert alert-success alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
      <%= flash[:success] %>
    </div>
<% end %>

app/views/layouts/_header_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheLense</title>

  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i" rel="stylesheet">

  <div id="showModal"></div>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid col-md-11">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <div id="logo">THE LENSE</div>
        </a>
      </div>


      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <!-- SEARCH BAR
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Go</button>
        </form> -->


        <!-- appearance based on whether the user as signed in or not -->
        <% if admin_signed_in? %>

            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="material-icons" style="font-size:30px; color: #000000; float: right; ">account_circle</i>
                  <div class="currentheaderusername"><%= current_admin.email %></div>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="/<%= current_user.username %>/published">My Boards</a></li>
                  <li><a href="/users/edit">Edit Profile</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
                  <% if Admin.where(email:current_admin.email).present? %>
                      <li><a href="/dashboard">Admin Tools</a></li>
                    <% end %>
                  <% if admin_signed_in? %>
                    <li><%= link_to('Sign Out Admin', destroy_admin_session_path, :method => :delete) %></li>
                  <% end %>
                </ul>
              </li>
            </ul>

        <% else %>
           
            <ul class="nav navbar-nav navbar-right">
              <% if admin_signed_in? %> 
                <li><%= link_to "Sign Out Admin", destroy_admin_session_path, :method => :delete %></li>
              <% end %>
            </ul>

        <% end %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->

    <!-- Secondary Nav -->
    <ul class="nav nav-pills col-md-11">
      <li><a href="/">Home</a></li>
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Categories <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <a href="/science">
            <li>Science &amp; Technology</li>
          </a>
          <a href="/business">
            <li>Business &amp; Finanace</li>
          </a>
          <a href="/politics">
            <li>Politics &amp; Economics</li>
          </a>
          <a href="/tv">
            <li>TV &amp; Movies</li>
          </a>
        </ul>
      </li>
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Discover <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <a href="#">
            <li>Editor's Picks</li>
          </a>
          <a href="#">
            <li>Most Recent</li>
          </a>
          <a href="#">
            <li>Most Popular</li>
          </a>
          <a href="#">
            <li>Most Saved</li>
          </a>
        </ul>
      </li>

      <!-- My Boards if user has signed in -->
      <% if admin_signed_in? %>
          <li role="presentation" class="dropdown" style="float:right;">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              My Boards <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/<%= current_user.username  %>/published">Published</a></li>
            <li><a href="/<%= current_user.username  %>/saved">Saved</a></li>
            <li><a href="/<%= current_user.username  %>/drafts">Drafts</a></li>
            </ul>
          </li>
      <% end %>
    </ul>
  </nav>


  <div class="col-md-12" id="fixedContainer">

    <% if user_signed_in? %>
        <a href="/forms/new">
          <div id="cur"><i class="material-icons md-48" , id="addCircle">add</i>
            <p class="text">Curate</p></div>
        </a>
    <% else %>
        <%= link_to(new_user_session_path, remote: true) do %>
            <div id="cur"><i class="material-icons md-48" , id="addCircle">add</i>
              <p class="text">Curate</p></div>
        <% end %>
    <% end %>
  </div>

</head>
<body>

app/views/layouts/_robin_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheLense</title>

  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i" rel="stylesheet">

  <div id="showModal"></div>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid col-md-11">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <div id="logo">THE LENSE</div>
        </a>
      </div>


      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <!-- SEARCH BAR
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Go</button>
        </form> -->


        <!-- appearance based on whether the user as signed in or not -->
        <% if user_signed_in? %>

            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="material-icons" style="font-size:30px; color: #000000; float: right; ">account_circle</i>
                  <div class="currentheaderusername"><%= current_user.username %></div>
                </a>
                <ul class="dropdown-menu">
                  <!-- <li><a href="/<%= current_user.username %>/published">My Boards</a></li> -->
                  <li><a href="/<%= current_user.username %>/published">Published</a></li>
                  <li><a href="/<%= current_user.username %>/drafts">Drafts</a></li>
                  <li><a href="/<%= current_user.username %>/saved">Saved</a></li>
                  <li><a href="/users/edit">Edit Profile</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
                  <% if Admin.where(email:current_user.email).present? %>
                      <li><a href="/dashboard">Admin Tools</a></li>
                    <% end %>
                  <% if admin_signed_in? %>
                    <li><%= link_to('Sign Out Admin', destroy_admin_session_path, :method => :delete) %></li>
                  <% end %>
                </ul>
              </li>
            </ul>

        <% else %>

            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign in / Sign Up", new_user_session_path, remote: true %></li>
              <% if admin_signed_in? %>
                <li><%= link_to('Sign Out Admin', destroy_admin_session_path, :method => :delete) %></li>
              <% end %>
            </ul>
        <% end %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->

    <!-- Secondary Nav -->
    <ul class="nav nav-pills col-md-11">
      <li><a href="/trending">Trending</a></li> 
      <% tren_cat = Form.all.map {|e| e.tag_list}.join(',').split(',').each_with_object(Hash.new(0)) {|b, hash| hash[b] += 1}.sort_by{ |k, v| v }.reverse.to_h.select {|x| x.start_with? 'cat_'} %>
      <% tren_cat.first(3).each do |f,v| %>
        <li><a href="/categories/<%= f[4..-1] %>"><%= f[4..-1].capitalize %></a></li>
      <% end %>
      <!-- <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Categories <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <% Category.all.each do |category| %>
            <a href="/categories/<%= category.category_name %>">
              <li><%= category.category_name %></li>
            </a>
          <% end %>
        </ul>
      </li> -->
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Discover <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <a href="#">
            <li>Editor's Picks</li>
          </a>
          <a href="#">
            <li>Most Recent</li>
          </a>
          <a href="#">
            <li>Most Popular</li>
          </a>
          <a href="#">
            <li>Most Saved</li>
          </a>
        </ul>
      </li>

      <!-- My Boards if user has signed in -->
      <% if user_signed_in? %>
          <!-- <li role="presentation" class="dropdown" style="float:right;">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              My Boards <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/<%= current_user.username  %>/published">Published</a></li>
            <li><a href="/<%= current_user.username  %>/saved">Saved</a></li>
            <li><a href="/<%= current_user.username  %>/drafts">Drafts</a></li>
            </ul>
          </li>
      <% end %>
    </ul> -->
  </nav>


  <div class="col-md-12" id="fixedContainer">

    <% if user_signed_in? %>
        <a href="/forms/new">
          <div id="cur"><i class="material-icons md-48" , id="addCircle">add</i>
            <p class="text">Curate</p></div>
        </a>
    <% else %>
        <%= link_to(new_user_session_path, remote: true) do %>
            <div id="cur"><i class="material-icons md-48" , id="addCircle">add</i>
              <p class="text">Curate</p></div>
        <% end %>
    <% end %>
  </div>

</head>
<body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109707538-1"></script>
  <script>
    var productionHost = 'www.thecurativ.com'; /* www.mixpanel.com */
  
    if (window.location.hostname.toLowerCase() == productionHost) {
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-109707538-1');
    };    
  </script>

  <title>The Curativ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width" />
  <%= yield :social_meta_tags %>
  <!-- start Mixpanel -->
  <script type="text/javascript">
  (function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
  var productionHost = 'www.thecurativ.com'; /* www.mixpanel.com */
  var stagingHost = 'lense-staging.herokuapp.com';
  var devHost = 'localhost';
  var stagingToken = "a114f0d602ff4e27d5d02308ac9e4b3b";
  var devToken = "da04b889782c5419d353e1948e20d3b8";
  var prodToken = "b22d7ccff223b0ac7dcd3e4f972b3f8f";
  /* If the hostname is anything other than your production domain, initialize the Mixpanel library with your Development Token */
  console.log(window.location.hostname.toLowerCase());
  if (window.location.hostname.toLowerCase() == devHost) {
    mixpanel.init(devToken);
  } else if (window.location.hostname.toLowerCase() == productionHost) {
    mixpanel.init(prodToken);
  } else if (window.location.hostname.toLowerCase() == stagingHost) {
    mixpanel.init(stagingToken);
  };
</script>
<!-- end Mixpanel -->
  <meta property="fb:app_id" content="<%= ENV['FACEBOOK_KEY'] %>" />
  <%= favicon_link_tag 'thecurativ-favicon.png'%>
</head>
<body ng-controller="bodyCtrl" ng-init="init()">
  <div layout="column" ng-cloak style="height:100%">
    <% if @skip_header %>      
    <% elsif current_user %>
      <%= render 'layouts/header'%>
    <% else %>      
    <% end %>
    <%= yield %>
  </div>
</body>
</html>